// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Xd5IVMXmDI2PMrs6cLwWJwT53LycCS4',
    appId: '1:1025308874936:web:d133b1b4d406a9aec33c4d',
    messagingSenderId: '1025308874936',
    projectId: 'erevive-a63ca',
    authDomain: 'erevive-a63ca.firebaseapp.com',
    storageBucket: 'erevive-a63ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm8zmfPFOI1iWZgLq-h-quqfGt5wlNEQk',
    appId: '1:1025308874936:android:772486dad5ed4084c33c4d',
    messagingSenderId: '1025308874936',
    projectId: 'erevive-a63ca',
    storageBucket: 'erevive-a63ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPL1BqphtKnCNCYE4aSCta27zBoKIvjTs',
    appId: '1:1025308874936:ios:518826f569168b40c33c4d',
    messagingSenderId: '1025308874936',
    projectId: 'erevive-a63ca',
    storageBucket: 'erevive-a63ca.appspot.com',
    iosBundleId: 'com.example.erevive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPL1BqphtKnCNCYE4aSCta27zBoKIvjTs',
    appId: '1:1025308874936:ios:518826f569168b40c33c4d',
    messagingSenderId: '1025308874936',
    projectId: 'erevive-a63ca',
    storageBucket: 'erevive-a63ca.appspot.com',
    iosBundleId: 'com.example.erevive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Xd5IVMXmDI2PMrs6cLwWJwT53LycCS4',
    appId: '1:1025308874936:web:38d91379ae3d749dc33c4d',
    messagingSenderId: '1025308874936',
    projectId: 'erevive-a63ca',
    authDomain: 'erevive-a63ca.firebaseapp.com',
    storageBucket: 'erevive-a63ca.appspot.com',
  );
}
